version: "3"
services:
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=IB
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,IB:PLAINTEXT
      - KAFKA_LISTENERS=CONTROLLER://:9093,BROKER://:9092,IB://:9094
      - KAFKA_ADVERTISED_LISTENERS=BROKER://kafka:9092,IB://:9094
    restart: always
  grafana:
    image: grafana/grafana:12.1
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    #  - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    #  - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana/datasources-ch.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus:v3.7.3
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  goflow2:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        VERSION: compose
        LDFLAGS: -X main.version=compose
    image: netsampler/goflow2
    depends_on:
      - kafka
    ports:
      - 8080:8080
      - 6343:6343/udp
      - 2055:2055/udp
    restart: always
    command:
      - -transport.kafka.brokers=kafka:9092
      - -transport=kafka
      - -transport.kafka.topic=flows
      - -format=bin
  db:
    image: clickhouse/clickhouse-server:25.11-alpine
    environment:
      - CLICKHOUSE_DO_NOT_CHOWN=1
      - CLICKHOUSE_PASSWORD=flow
    ports:
      - 8123:8123
    restart: always
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d/
      #- ../../pb/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
      # the following files have 101:101 as owner
      - ./clickhouse/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
      - ./clickhouse/protocols.csv:/var/lib/clickhouse/user_files/protocols.csv
    depends_on:
      - kafka
