apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   version: 1
   editable: true
 - name: ClickHouse
   type: vertamedia-clickhouse-datasource
   typeLogoUrl: ''
   access: proxy
   url: http://db:8123
   password: ''
   user: ''
   database: ''
   basicAuth: true
   basicAuthUser: 'default'
   secureJsonData:
     basicAuthPassword: 'flow'
   withCredentials: false
   isDefault: true
   secureJsonFields: {}
   version: 3
   readOnly: false
